name: Terraform and Docker Setup

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Install Google Cloud SDK
      run: |
        curl https://sdk.cloud.google.com | bash
        source $HOME/google-cloud-sdk/path.bash.inc
        gcloud auth activate-service-account --key-file=${{ secrets.GCP_KEY_FILE }}

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform configuration
      run: terraform apply -auto-approve

    - name: Get the external IP of the instance
      id: get_ip
      run: |
        INSTANCE_IP=$(terraform output -raw instance_external_ip)
        echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV

    - name: Install Docker on the instance
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} nikhil@${{ env.INSTANCE_IP }} << EOF
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl enable docker
          sudo systemctl start docker
        EOF
    
    - name: Run DeepSeek Model and WebUI via Docker
      run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} nikhil@${{ env.INSTANCE_IP }} <<EOF
            docker run -d -p 8080:8080 --name deepseek-webui openwebui/ollama-webui
            docker run -d --name deepseek-model deepseek-model:latest
          EOF
    
    - name: Confirm WebUI is Running
      run: |
            ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} nikhil@${{ env.INSTANCE_IP }} <<EOF
              curl http://localhost:8080
            EOF
    